# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5393a1541b224a38990e8fcb3321815a356c9bf60781f35d38c5e651445227351589438ba8dc567a31cc8832e428c430de912cc2f811c97694048f68477d66fd

test:
  secret_key_base: 62194d1f6f8a1cc99baa2f317e60316357a2e5f51fc22047c7eeb0d3d71c46b730acd5e80bf33919f861cc833035bd6a8b84d41e38735a132f7191320c2fb65d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
